using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;

namespace spaceShooter
{

    /// <summary>
    /// A weapon shot generated by an player or enemy
    /// </summary>
    class Weapon
    {
        #region Fields

        Vector2 velocity = Vector2.Zero;
        int damage;
        int weaponType;
        Vector2 location;

        Texture2D sprite;
        Rectangle drawRectangle;
        #endregion

        #region Constructors

        public Weapon(int weaponType, Vector2 location, int damage)
        {
            this.damage = damage;
            this.weaponType = weaponType;
            this.location = location;

            //Sets the specifics for each weapon
            if(weaponType == 0)
            {
                velocity.X = 5;
                velocity.Y = 0;
            }
            if (weaponType == 1)
            {
                velocity.X = 10;
                velocity.Y = 0;
            }
            if (weaponType == 2)
            {
                velocity.X = 10;
                velocity.Y = -10;
            }
            if (weaponType == 3)
            {
                velocity.X = -10;
                velocity.Y = 0;
            }
            if (weaponType == 4)
            {
                velocity.X = 10;
                velocity.Y = 10;
            }
        }

        #endregion

        #region Properties
        public Texture2D Sprite
        {
            set { sprite = value; }
        }

        public Vector2 Location
        {
            get { return location; }
        }

        #endregion

        #region Methods
        public void Draw(SpriteBatch spriteBatch)
        {
            drawRectangle = new Rectangle((int)(location.X - sprite.Width / 2), (int)(location.Y - sprite.Height / 2), sprite.Width, sprite.Height);
            spriteBatch.Draw(sprite, drawRectangle, Color.White);
        }

        public void Update(GameTime gametime, Vector2 window)
        {
            location.X += (int) velocity.X;
            drawRectangle.X = (int)location.X;

            location.Y += (int)velocity.Y;
            drawRectangle.Y = (int)location.Y;
        }

        #endregion
    }
}
